config/routes.rb
Exercise::Application.routes.draw do
 resources :users
  root  to: 'users#index'
  match '/creat', to:'users#creat',via: [:get,:post]
 match '/register', to: 'users#register',via:[:get,:post]
  match '/signout', to: 'users#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,presence: true, length: {maximum: 20}
  EMAIL=/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email,presence: true, format: { with: EMAIL } ,
		uniqueness: { case_sensitive: false}
  validates :password, length: { minimum: 6}



before_create :create_remember

  def User.new_remember
  	  SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
	  Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember
	self.remember = User.encrypt(User.new_remember)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
include UsersHelper
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def register
  	@title="Register"
	@user=User.new
	if request.post? and params[:user]
		@user=User.new(user_params)
		if @user.save
			redirect_to :action=>"index"
		else
			render 'register'
		end
	end
		
  end

  def creat
  	@title="Login"
	if request.post? and params[:user]
		@user=User.new(log_params)
		user=User.find_by_name_and_password(@user.name,@user.password)
		if user
			redirect_to :action=>"index"
		else
		 flash.now[:error] = 'Invalid email/password combination'
			redirect_to :action=>"register"
		end
	end

  end
end
  
  def index
  	@title="Home"
  end
  private

  def user_params
  	params.require(:user).permit(:name,:email,:password)
  end
  def log_params
  	params.require(:user).permit(:name,:password)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  end
  def register
  	@title="Register"
	@user=User.new
	if request.post? and params[:user]
		@user=User.new(user_params)
		if @user.save
			redirect_to @user
		else
		render 'register'
		end
	end
		
  end

  def creat
  	@title="Login"
	if request.post? and params[:user]
		@user=User.new(log_params)
		user=User.find_by_name_and_password(@user.name,@user.password)
		if user
		 sign_in user
		redirect_to user
		else
		 flash.now[:error] = 'Invalid email/password combination'
			redirect_to :action=>"register"
		end
	end

  end
  def destroy
   	 sign_out
        redirect_to register_path
  end

  def index
  
  	@title="Home"
  end
  private

  def user_params
  	params.require(:user).permit(:name,:email,:password)
  end
  def log_params
  	params.require(:user).permit(:name,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def sign_in(user)
	remember= User.new_remember
	cookies.permanent[:remember] = remember
	user.update_attribute(:remember, User.encrypt(remember))
	self.current_user = user
  end
  def current_user=(user)
	@current_user = user
  end
   def current_user
       	remember = User.encrypt(cookies[:remember])
	@current_user ||= User.find_by(remember: remember)
   end
   def signed_in?
       !current_user.nil?
   end
   def sign_out
       self.current_user = nil
       cookies.delete(:remember)
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
<div class="container">
<nav>
<ul class="nav pull-right">
   <% if signed_in? %> 
   <li id="fat-menu" class="dropdown">
   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
   Account <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
    <li><%= link_to "Profile", current_user %></li>
     <li><%= link_to "Settings", '#' %></li>
     <li class="divider"></li>
     <li>
     <%= link_to "Sign out", signout_path, method: "delete" %>
     </li>
      </ul>
      </li>
      <% else %>
      <li><%=link_to "Register",register_path%></li>  
      <li><%= link_to "Login", creat_path%></li>
      <% end %>
</ul>
</nav>
</div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %> 
	 <div id="error_explanation"> 
	 <div class="alert alert-error">  
	注意！这里有 <%= pluralize(@user.errors.count, "错误") %>:
	</div>
	<ul>
	  <% @user.errors.full_messages.each do |msg| %> 
	    <li>* <%= msg %></li> 
	    <% end %> 
	</ul>
	 </div>
<% end %> 

app/views/users/creat.html.erb
<div class="span6 offset6">
<div class="login">
<h2>Login</h2>

<%=form_for :user do |f|%>
		<legend>Enter Your Detials</legend>
		<%=f.label :Name%>
		<%=f.text_field :name%>
		
		<%=f.label :Password%>
		<%=f.password_field :password%><br>
		
	<br>	<%=submit_tag "Login", class: "btn btn-large btn-primary"%>
<%end%>
<li> <%=link_to("还没有注册？",{action: "register"})%></li>
 </div>
 </div>

app/views/users/index.html.erb
<h1>Index<h1>

app/views/users/register.html.erb
<div class="container">
<div class="row">
 <div class="span6">
                  <div class="slogan"> 
                            <h1 class="slogan-title">计划让生活更流畅</h1>
                     
                     <p class="slogan-description">  计划任务网站旨在让人们生活更有序，简洁，  完全免费的服务</p>
                       </div>
                       </div>

<div class="span6 offset8">
    <h2>Register</h2>

    <%= form_for :user do |f| %>
		<legend>Enter Your Detial</legend>
		
		<%=f.label :Name%>
		<%=f.text_field :name%>
		
		<%=f.label :Email%>
		<%=f.text_field :email%>
		
		<%=f.label :Password%>
		<%=f.password_field :password%>
		
	
		<br>	<%=submit_tag "Register", class: "btn btn-large btn-primary"%>
	        <%=render'shared/error_messages',  object: f.object %>
      <%end%>
   </div>	    
		</div>
		</div>

	<div class="container">	    
	<div class="row">
		<div class="span4 offset1">
		   <%= image_tag "tasktab.png" %>
		   </div>
		<div class="span4 offset9">
		  <h3>合理的规划自己的时间</h3>
		  <h4>生活需要适当的安排</BR>
		     <BR> 提高生活的质量</BR>	
		    <br> 充分利用自己的时间</BR>
		     
		  </h4>
		  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>